window.OPEN_MOSQUE_PRESETS = [
  {
    name: "Centre Culturel Islamique de Laval - Khalid Ben El Walid",
    slug: "ccil-kbw-laval",
    city: "Laval",
    address: "1330 Rue Antonio, Laval, QC H7V 3N4",
    websiteUrl: "https://ccil-kbw.com/",
    sourceUrl: "https://ccil-kbw.com/",
  },
  {
    name: "Centre Communautaire Musulman IQRA",
    slug: "centre-iqra-laval",
    city: "Laval",
    address: "960 Bd du Cure-Labelle, Laval, QC H7V 2V5",
    websiteUrl: "https://centreiqra.org/",
    sourceUrl: "https://centreiqra.org/",
  },
  {
    name: "Masjid Al-Itissam",
    slug: "masjid-al-itissam-laval",
    city: "Laval",
    address: "600 Boulevard des Laurentides, Laval, QC H7G 2V5",
    websiteUrl: "https://al-itissam.org/",
    sourceUrl: "https://al-itissam.org/",
  },
  {
    name: "Centre Aljisr",
    slug: "centre-aljisr-laval",
    city: "Laval",
    address: "3005 Boulevard Cartier O, Laval, QC H7V 1J3",
    websiteUrl: "https://centrealjisr.com/",
    sourceUrl: "https://centrealjisr.com/",
  },
  {
    name: "Masjid Al-Forqane",
    slug: "masjid-al-forqane-laval",
    city: "Laval",
    address: "3390 Bd Sainte-Rose, Laval, QC H7R 5E8",
    websiteUrl: "",
    sourceUrl: "https://www.yellowpages.ca/search/si/1/Mosques/Terrebonne%2BQC",
  },
  {
    name: "Al Firdaws Mosque - Centre Communautaire Musulman de Terrebonne",
    slug: "mosquee-al-firdaws-terrebonne",
    city: "Terrebonne",
    address: "3660 Chemin Gascon, Terrebonne, QC J6X 4J1",
    websiteUrl: "https://mosqueealfirdaws.net/",
    sourceUrl: "https://mosqueealfirdaws.net/",
  },
  {
    name: "Islamic Centre of Quebec",
    slug: "islamic-centre-of-quebec",
    city: "Saint-Laurent",
    address: "2520 Chemin Laval, Saint-Laurent, QC H4L 3A1",
    websiteUrl: "https://www.icqmontreal.com/",
    sourceUrl: "https://www.icqmontreal.com/",
  },
  {
    name: "Al-Andalous Islamic Center",
    slug: "al-andalous-islamic-center",
    city: "Saint-Laurent",
    address: "816 Av. Sainte-Croix, Saint-Laurent, QC H4L 3Y4",
    websiteUrl: "",
    sourceUrl: "https://mawaqit.net/en/m/al-andalous-mtl",
  },
  {
    name: "Islamic Center of West Island",
    slug: "islamic-center-west-island",
    city: "Dollard-des-Ormeaux",
    address: "31 Rue Montrose, Dollard-des-Ormeaux, QC",
    websiteUrl: "https://icwestisland.com/",
    sourceUrl: "https://icwestisland.com/",
  },
  {
    name: "Khadijah Islamic Center",
    slug: "khadijah-islamic-center",
    city: "Montreal",
    address: "2385 Centre St, Montreal, QC H3K 1J6",
    websiteUrl: "https://khadijahmtl.org/",
    sourceUrl: "https://khadijahmtl.org/",
  },
  {
    name: "Islamic Services of Quebec",
    slug: "islamic-services-of-quebec",
    city: "Montreal",
    address: "2038 Boul. Saint-Laurent, Montreal, QC H2X 2T2",
    websiteUrl: "https://isqc.ca/",
    sourceUrl: "https://isqc.ca/",
  },
  {
    name: "Muaz Ibn Jabal Islamic Center",
    slug: "muaz-ibn-jabal-islamic-center",
    city: "Montreal",
    address: "6484 Av. Victoria, Montreal, QC H4P 1P4",
    websiteUrl: "https://sites.google.com/view/muazbinjabalislamiccentre/home",
    sourceUrl: "https://moonode.com/entity/muaz-ibn-jabal-islamic-ce-851888-6338-avenue-victoria-montreal-qc-h3w-2s5-canada",
  },
  {
    name: "Centre Islamique Bilal du Quebec",
    slug: "centre-islamique-bilal",
    city: "Montreal",
    address: "4139 Rue Jean-Talon O, Montreal, QC H4P 1W6",
    websiteUrl: "",
    sourceUrl: "https://moonode.com/entity/centre-islamique-bilal-du-291866-4139-rue-jean-talon-o-montreal-qc-h4p-1w6-canada",
  },
  {
    name: "Masjid Baitul Mukarram",
    slug: "masjid-baitul-mukarram",
    city: "Montreal",
    address: "4225 Avenue de Courtrai, Montreal, QC H3S 1B8",
    websiteUrl: "",
    sourceUrl: "https://moonode.com/entity/masjid-baitul-mukarram-870023-4225-avenue-de-courtrai-montreal-qc-h3s-1b8-canada",
  },
  {
    name: "Fondation Message de l'Islam",
    slug: "fondation-message-islam",
    city: "Montreal",
    address: "10555 Boul. St-Laurent, Montreal, QC H3L 2P5",
    websiteUrl: "http://www.davetvakfi.com/",
    sourceUrl: "https://moonode.com/entity/fondation-message-de-lis-138240-10555-boul-st-laurent-montreal-qc-h3l-2p5-canada",
  },
  {
    name: "Ridwan Centre Communautaire Darlington",
    slug: "ridwan-centre-darlington",
    city: "Montreal",
    address: "2876 Rue Goyer, Montreal, QC H3S 1H3",
    websiteUrl: "https://www.facebook.com/centrecommunautairedarlington",
    sourceUrl: "https://moonode.com/entity/ridwan-centre-communautai-193642-2876-rue-goyer-montreal-qc-h3s-1h3-canada",
  },
  {
    name: "Al Hadara",
    slug: "al-hadara-montreal",
    city: "Montreal",
    address: "615 Rue Belmont, Montreal, QC H3B 2L8",
    websiteUrl: "",
    sourceUrl: "https://moonode.com/entity/al-hadara-895421-615-rue-belmont-montreal-qc-h3b-2l8-canada",
  },
  {
    name: "Mosquee Elfath",
    slug: "mosquee-elfath",
    city: "Montreal",
    address: "11660 Bd Riviere-des-Prairies, Montreal, QC H1C 1P9",
    websiteUrl: "",
    sourceUrl: "https://prayersconnect.com/mosques/search/Mascouche%2C%20Quebec%2C%20Canada/45.74965%2C-73.59956/45.74965%2C-73.59956",
  },
  {
    name: "Mosquee NDG",
    slug: "mosquee-ndg",
    city: "Montreal",
    address: "6277 Rue Saint-Jacques, Montreal, QC H4B 1T8",
    websiteUrl: "",
    sourceUrl: "https://mosque-ndg.wheree.com/",
  },
  {
    name: "Information Centre on Islam",
    slug: "information-centre-on-islam",
    city: "Montreal",
    address: "2054 St-Denis #2, Montreal, QC H2X 3K7",
    websiteUrl: "",
    sourceUrl: "https://www.islamicsupremecouncil.com/masajid-mosques-and-islamic-centres-in-canada/",
  },
];
